#!/usr/bin/env python2
# -*- python -*-

from subprocess import (
    CalledProcessError,
    check_call,
)

# If the user's environment has "juju-origin: ppa" set, they will
# automatically have access to python-charmhelpers and python-shelltoolbox.
# However, we want to support environments that use the non-PPA environment as
# well.  To do so, we need to install the Juju PPA, which we will do with a
# couple of functions that are actually maintained in python-shelltoolbox.
import bootstrap_utils
bootstrap_utils.install_extra_repositories('ppa:juju/pkgs')

# python-shelltoolbox is installed as a dependency of python-charmhelpers.
check_call(['apt-get', 'install', '-y', 'python-charmhelpers'])


# These modules depend on charmhelpers and shelltoolbox being installed so they
# must not be imported until those packages are available.
from charmhelpers import (
    get_config,
    log,
    log_entry,
    log_exit,
)
from shelltoolbox import (
    apt_get_install,
    install_extra_repositories,
)

from utils import (
    cmd_log,
    config_json,
    fetch_api,
    fetch_gui,
    save_or_create_certificates,
    setup_gui,
    setup_nginx,
)


DEB_DEPENDENCIES = (
    'bzr', 'curl', 'haproxy', 'imagemagick', 'make', 'nginx', 'nodejs', 'npm',
    'openssl', 'python-launchpadlib', 'zookeeper',
)
REPOSITORIES = ('ppa:chris-lea/node.js', 'ppa:frankban/ppa')


def get_dependencies():
    log('Installing dependencies.')
    cmd_log(install_extra_repositories(*REPOSITORIES))
    cmd_log(apt_get_install(*DEB_DEPENDENCIES))


def main():
    config = get_config()
    get_dependencies()
    release_tarball = fetch_gui(
        config['juju-gui-source'], config['command-log-file'])
    setup_gui(release_tarball)
    setup_nginx()
    save_or_create_certificates(
        config['ssl-cert-path'], config.get('ssl-cert-contents'),
        config.get('ssl-key-contents'))
    fetch_api(config['juju-api-branch'])
    config_json.set(config)


if __name__ == '__main__':
    log_entry()
    try:
        main()
    except CalledProcessError as e:
        log('Exception caught:')
        log(e.output)
        raise
    finally:
        log_exit()
